# 这里的配置不是完整的， 完整的请看theme目录下的 config.yml 文件

nav:
  logo: https://s3.babudiu.com/iuxt/public/boob.png
  display_title: true
  fixed: true # 固定导航栏

menu:
  首页: / || fas fa-home
  归档: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  工具||fas fa-list:
    小游戏: https://bbk-games.zahui.fan/ || fas fa-gamepad
    Aria2: https://aria2.babudiu.com/ || fas fa-download
    网盘: https://file.babudiu.com/ || fa-solid fa-file
  林克: /link/ || fa-solid fa-paperclip
  关于: /about/ || fa-brands fa-apple fa-bounce

code_blocks:
  # Code block theme: darker / pale night / light / ocean / false
  theme: light
  macStyle: true
  # Code block height limit (unit: px)
  height_limit: false
  word_wrap: false

  # Toolbar
  copy: true
  language: true
  # true: shrink the code blocks | false: expand the code blocks | none: expand code blocks and hide the button
  shrink: false
  fullpage: false

social:
  fab fa-github: https://github.com/iuxt || Github
  fas fa-envelope: mailto:x@zahui.fan || Email
  fa-brands fa-bilibili: https://space.bilibili.com/165330963 || Bilibili
  fa-brands fa-stack-overflow: https://stackoverflow.com/users/15620461/ || StackOverflow
  fa-solid fa-square-rss: /atom.xml || RSS


search:
  # Choose: algolia_search / local_search / docsearch
  # leave it empty if you don't need search
  use: local_search
  placeholder: 搜搜搜

  # Local Search
  local_search:
    # Preload the search data when the page loads.
    preload: false
    # Show top n results per article, show all results by setting to -1
    top_n_per_article: 1
    # Unescape html strings to the readable one.
    unescape: false
    CDN:


favicon: /favicon.ico

avatar:
  img: https://s3.babudiu.com/iuxt/public/dog.svg
  effect: false
disable_top_img: false
enter_transitions: false
index_img: 'https://s3.babudiu.com/iuxt/public/cloud-dark.svg'

index_site_info_top: 30% # 这个是标题等距离顶部的比例
index_top_img_height: 30em # 这里是首页大图的高度，默认是满屏幕的， 支持写法 300px/300em/300rem 
display_mode: light # 默认是夜间模式还是白天模式 dark/light

# If the banner of page not setting, it will show the top_img
default_top_img: https://s3.babudiu.com/iuxt/public/Lollipop2.svg

cover:
  # display the cover or not (是否顯示文章封面)
  index_enable: true
  aside_enable: true
  archives_enable: true
  # the position of cover in home page (封面顯示的位置)
  # left/right/both
  position: left
  # When cover is not set, the default cover is displayed (當沒有設置cover時，默認的封面顯示)
  default_cover:
    - 'https://s3.babudiu.com/iuxt/public/skeleton1.svg'


# Replace Broken Images (替換無法顯示的圖片)
error_img:
  flink: /img/friend_404.gif
  post_page: /img/404.jpg

# A simple 404 page
error_404:
  enable: true
  subtitle: 'Page Not Found 页面没有找到'
  background: https://s3.babudiu.com/iuxt/public/404.webp

post_meta:
  page: # Home Page
    date_type: created # created or updated or both 主頁文章日期是創建日或者更新日或都顯示
    date_format: date # date/relative 顯示日期還是相對日期
    categories: true # true or false 主頁是否顯示分類
    tags: false # true or false 主頁是否顯示標籤
    label: true # true or false 顯示描述性文字
  post:
    position: left
    date_type: both # created or updated or both 文章頁日期是創建日或者更新日或都顯示
    date_format: date # date/relative 顯示日期還是相對日期
    categories: true # true or false 文章頁是否顯示分類
    tags: true # true or false 文章頁是否顯示標籤
    label: true # true or false 顯示描述性文字


index_post_content:
  method: 3
  length: 500 # if you set method to 2 or 3, the length need to config

# toc (目錄)
toc:
  post: true
  page: false
  number: true
  expand: false
  style_simple: false
  scroll_percent: true

post_copyright:
  enable: true
  decode: false
  author_href:
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# Related Articles
related_post:
  enable: true
  limit: 6 # Number of posts displayed
  date_type: updated # or created or updated 文章日期顯示創建日或者更新日

# figcaption (圖片描述文字)
photofigcaption: false

post_pagination: 1

noticeOutdate:
  enable: true
  style: flat # style: simple/flat
  limit_day: 365 # When will it be shown
  position: top # position: top/bottom
  message_prev: 此文章距离发布已经
  message_next: 天了，内容可能已经过时，请自行判断是否可用或联系博主更新。

share:
  # Choose: sharejs / addtoany
  # Leave it empty if you don't need share
  use: sharejs

  # Share.js
  # https://github.com/overtrue/share.js
  sharejs:
    sites: facebook,twitter,wechat,weibo,qq

comments:
  use: Giscus # Valine,Disqus
  text: true # Display the comment name next to the button
  lazyload: false
  count: false # Display comment count in post's top_img
  card_post_count: false # Display comment count in Home Page

giscus:
  repo: iuxt/iuxt.github.io
  repo_id: R_kgDOMszkdA
  category_id: DIC_kwDOMszkdM4CiMyw
  light_theme: light
  dark_theme: dark
  js: https://giscus.babudiu.com/client.js
  option:

footer:
  owner:
    enable: false
    since: 2020
  custom_text: |
    <a href='https://www.upyun.com/?utm_source=lianmeng&utm_medium=referral'>
      本网站由<img src='https://s3.babudiu.com/iuxt/public/upyun.svg' alt='又拍云' width='70' height='28' style="vertical-align:bottom">
      提供CDN加速/云存储服务
    </a>
    </br>
    <a href="https://beian.miit.gov.cn/" target="_blank">沪ICP备2021015230号-1</a>
  copyright: false # Copyright of theme and framework

baidu_analytics: 50b516d50102c8c9ac5f80529b81ca17
google_analytics: G-YN0WWZGVYN

theme_color:
  enable: true
  main: "#5a544b"

# Beautify (美化頁面顯示)
beautify:
  enable: true
  field: post # site/post
  title_prefix_icon: '\f2db'
  title_prefix_icon_color: '#F47466'

hr_icon:
  enable: true
  icon: # the unicode value of Font Awesome icon, such as '\3423'
  icon_top:

subtitle:
  enable: true
  effect: true
  typed_option:
  source: false
  sub: 
  - ♥ Do have faith in what you're doing.
  - 欲穷千里目，更上一层楼。
  - 学而不思则罔，思而不学则殆。


index_layout: 1

aside:
  enable: true
  hide: false
  button: true
  mobile: true # display on mobile
  position: right # left or right
  display:
    archive: true
    tag: true
    category: true
  card_author:
    enable: true
    description: "张理坤的博客"
    button:
      enable: true
      icon: fab fa-github
      text: Follow Me
      link: https://github.com/iuxt
  card_announcement:
    enable: true
    content: |
      此博客为我记录运维工作总结所用，供网友阅读参考，如有侵权，请通知我，我会核实后进行处理。</br>
      <strong style="color: red;">欢迎加入技术交流群：</strong>
      <div class="aside-qrcode" >
      <img src="https://src.babudiu.com/card/wechat_ops_group.JPG" title="微信群" width="100%" height="auto">
      </div>
  card_recent_post:
    sort: updated # date or updated

busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

darkmode:
  enable: true
  button: true
  autoChangeMode: false

lightbox: fancybox

note:
  style: flat
  icons: true
  border_radius: 3
  light_bg_offset: 0

instantpage: false

lazyload:
  enable: true
  field: post # site/post
  placeholder: https://s3.babudiu.com/iuxt/public/nes.gif
  blur: false


CDN:
  internal_provider: local
  third_party_provider: local

mask:
  header: true
  footer: false

# Insert the code to head (before '</head>' tag) and the bottom (before '</body>' tag)
# 插入代码到头部 </head> 之前 和 底部 </body> 之前
inject:
  head:
    # - <link rel="stylesheet" href="https://cdn.staticfile.org/lxgw-wenkai-screen-webfont/1.7.0/style.min.css" />
    - <link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/lxgw-wenkai-screen-webfont/1.7.0/style.min.css" />
    # - <link rel="stylesheet" href="https://s3.babudiu.com/iuxt/libs/lxgw-wenkai-screen-webfont/1.7.0/style.min.css" />
  bottom:
    # - <script src="xxxx"></script>

font:
  global_font_size:
  code_font_size:
  font_family: '"LXGW WenKai Screen", sans-serif;'
  code_font_family:

pwa:
  enable: true
  manifest: /site.webmanifest
  apple_touch_icon: /apple-touch-icon.png
  favicon_32_32: /favicon-32x32.png
  favicon_16_16: /favicon-16x16.png
  mask_icon: /safari-pinned-tab.svg
